#!/bin/bash
# Generated by src/cli/install-gateway-agent.ts. Regenerate it rather than edit it: every path below
# is a deployment's, and a hand edit is a decision recorded nowhere.
set -uo pipefail

# Everything below this line writes private runtime state, and the runtime creates its own
# directories with no mode at all (ADR-0014), so the mask is the floor rather than each caller.
umask 077

export PATH='/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
export OPENCLAW_CONFIG_PATH='/absolute/path/outside/this/repository/openclaw.json'
export OPENCLAW_STATE_DIR='/absolute/path/outside/this/repository/runtime-state'

runtime='/absolute/path/outside/this/repository/runtime/node_modules/openclaw/openclaw.mjs'
logs_dir='/absolute/path/outside/this/repository/logs'
capture='/absolute/path/outside/this/repository/logs/gateway.err.log'
capture_max_bytes=5242880
scratch_root='/tmp/openclaw'
lock_dir="${TMPDIR:-/tmp}/openclaw-$(id -u)"

# launchd cannot open a capture file on the external volume the logs live on — it exits EX_CONFIG
# before the job runs — so the wrapper opens it, being the process that already writes there.
# Only stderr is kept: the runtime's own log is a superset of its stdout, and ADR-0014 rotates that.
start_capture() {
  mkdir -p "$logs_dir" || exit 2
  chmod 700 "$logs_dir" || exit 2
  if [ -f "$capture" ] && [ "$(stat -f %z "$capture")" -ge "$capture_max_bytes" ]; then
    mv -f "$capture" "${capture%.log}.1.log"
  fi
  : >>"$capture" || exit 2
  chmod 600 "$capture" || exit 2
  exec >/dev/null 2>>"$capture"
}

refuse() {
  echo "syrax pre-flight: $1" >&2
  exit 2
}

warn() {
  echo "syrax pre-flight: $1" >&2
}

# ADR-0015: the runtime creates this at 0700 and then enforces only that nobody else can write it,
# so a world-readable scratch root passes its own check. Absent is fine — it creates it.
assert_private() {
  local directory=$1 mode
  [ -d "$directory" ] || return 0
  mode=$(stat -f %Lp "$directory")
  [ "$mode" = 700 ] || refuse "$directory is mode $mode, expected 700."
}

# ADR-0017: the lock directory does not exist until a lock is taken, so there is nothing to assert
# on a first run — and mkdir -p leaves an existing directory's mode alone.
ensure_private() {
  local directory=$1
  mkdir -p "$directory" || refuse "$directory could not be created."
  chmod 700 "$directory" || refuse "$directory could not be made private."
  assert_private "$directory"
}

# ADR-0010's asymmetry: an unresolved ref is a gateway that comes up and refuses every turn, which
# is worse than not coming up. A posture finding should not cost the Owner their chatbot.
audit_secrets() {
  local audited
  node "$runtime" secrets audit --check
  audited=$?
  case $audited in
    0) ;;
    1) warn "the secrets audit reports a posture finding; starting anyway." ;;
    *) refuse "the secrets audit exits $audited: a ref the runtime cannot resolve." ;;
  esac
}

# ADR-0005 closed this hole once and nothing has watched it since; off, a cut leaves the mini dark.
# It warns rather than refuses: a gateway that cannot survive a power cut still answers today.
check_restarts_after_power_loss() {
  local setting
  setting=$(pmset -g | awk '$1 == "autorestart" { print $2 }')
  [ "$setting" = 1 ] || warn "pmset autorestart is $setting: a power cut leaves the mini dark."
}

preflight() {
  assert_private "$scratch_root"
  ensure_private "$lock_dir"
  # The logs directory is not checked here: start_capture made it private before this ran.
  audit_secrets
  check_restarts_after_power_loss
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
  start_capture
  preflight
  exec node "$runtime" gateway
fi
