#!/bin/bash
# Generated by src/cli/install-monitor-agent.ts. Regenerate it rather than edit it: every path below
# is a deployment's, and a hand edit is a decision recorded nowhere.
set -uo pipefail

# The counters are private runtime state, and this unit creates the directory it writes them in.
umask 077

export PATH='/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'

preflight_name='syrax lane monitor pre-flight'
logs_dir='/absolute/path/outside/this/repository/logs'
capture='/absolute/path/outside/this/repository/logs/monitor.err.log'
capture_max_bytes=5242880

start_capture() {
  mkdir -p "$logs_dir" || exit 2
  chmod 700 "$logs_dir" || exit 2
  if [ -f "$capture" ] && [ "$(stat -f %z "$capture")" -ge "$capture_max_bytes" ]; then
    mv -f "$capture" "${capture%.log}.1.log"
  fi
  : >>"$capture" || exit 2
  chmod 600 "$capture" || exit 2
  exec >/dev/null 2>>"$capture"
}

refuse() {
  echo "$preflight_name: $1" >&2
  exit 2
}

warn() {
  echo "$preflight_name: $1" >&2
}

unit='/absolute/path/to/this/checkout/src/cli/serve-monitor.ts'
deployment='/absolute/path/outside/this/repository/deployment.json'
monitor_state='/absolute/path/outside/this/repository/lane-monitor'
secrets_store='/absolute/path/outside/this/repository/secrets/syrax.json'

ensure_private() {
  local directory=$1
  mkdir -p "$directory" || refuse "$directory could not be created."
  chmod 700 "$directory" || refuse "$directory could not be made private."
}

# A restart that lost the counters would hand back an allowance already spent, which is the whole
# reason this unit is separate — so the directory they live in is a refusal rather than a warning.
check_state() {
  ensure_private "$monitor_state"
}

# ADR-0010: the store's mode is its protection, so a readable one is refused rather than used. The
# hatch resolves the key at the moment it calls, and refusing here is refusing once instead.
check_secrets_store() {
  local mode
  [ -f "$secrets_store" ] || refuse "$secrets_store is not there: the wizard has not run."
  mode=$(stat -f %Lp "$secrets_store")
  [ "$mode" = 600 ] || refuse "$secrets_store is mode $mode, expected 600."
}

preflight() {
  check_state
  check_secrets_store
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
  start_capture
  preflight
  exec node "$unit" "$deployment"
fi
