#!/bin/bash
# Generated by src/cli/install-academic-agent.ts. Regenerate it rather than edit it: every path below
# is a deployment's, and a hand edit is a decision recorded nowhere.
set -uo pipefail

# The desk's scratch holds one Proposal input at a time, and a Proposal input is the Owner's diary.
umask 077

export PATH='/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'

preflight_name='syrax academic desk pre-flight'
logs_dir='/absolute/path/outside/this/repository/logs'
capture='/absolute/path/outside/this/repository/logs/academic.err.log'
capture_max_bytes=5242880

start_capture() {
  mkdir -p "$logs_dir" || exit 2
  chmod 700 "$logs_dir" || exit 2
  if [ -f "$capture" ] && [ "$(stat -f %z "$capture")" -ge "$capture_max_bytes" ]; then
    mv -f "$capture" "${capture%.log}.1.log"
  fi
  : >>"$capture" || exit 2
  chmod 600 "$capture" || exit 2
  exec >/dev/null 2>>"$capture"
}

refuse() {
  echo "$preflight_name: $1" >&2
  exit 2
}

warn() {
  echo "$preflight_name: $1" >&2
}

unit='/absolute/path/to/this/checkout/src/cli/serve-academic.ts'
deployment='/absolute/path/outside/this/repository/deployment.json'
academic_state='/absolute/path/outside/this/repository/academic-desk'
secrets_store='/absolute/path/outside/this/repository/secrets/syrax.json'
academic_os='/absolute/path/to/the/academic-os/checkout/dist/src/cli.js'
ntulearn='/absolute/path/to/the/ntulearn/checkout/src/cli.mjs'

ensure_private() {
  local directory=$1
  mkdir -p "$directory" || refuse "$directory could not be created."
  chmod 700 "$directory" || refuse "$directory could not be made private."
}

check_state() {
  [ -n "$academic_state" ] || refuse "the deployment names no academic products."
  ensure_private "$academic_state"
}

# ADR-0010: the store's mode is its protection, and this unit reads the bot token out of it to post
# the brief — so a readable store is refused here rather than at seven in the morning.
check_secrets_store() {
  local mode directory
  [ -f "$secrets_store" ] || refuse "$secrets_store is not there: the wizard has not run."
  mode=$(stat -f %Lp "$secrets_store")
  [ "$mode" = 600 ] || refuse "$secrets_store is mode $mode, expected 600."
  directory=$(dirname "$secrets_store")
  mode=$(stat -f %Lp "$directory")
  [ "$mode" = 700 ] || refuse "$directory is mode $mode, expected 700."
}

# A product that is not there answers nothing, and the brief says so on the morning it happens.
# Starting without one beats a heartbeat that stops for a checkout nobody has built yet.
check_products() {
  [ -f "$academic_os" ] || warn "$academic_os is not there: run npm ci && npm run build in academic-os."
  [ -f "$ntulearn" ] || warn "$ntulearn is not there: the ntulearn checkout is not where the deployment says."
}

preflight() {
  check_state
  check_secrets_store
  check_products
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
  start_capture
  preflight
  exec node "$unit" "$deployment"
fi
