#!/bin/bash
# Generated by src/cli/install-search-agent.ts. Regenerate it rather than edit it: every path below
# is a deployment's, and a hand edit is a decision recorded nowhere.
set -uo pipefail

# The index holds the extracted text of private documents verbatim, and this unit creates the
# directories it writes. The mask is the floor rather than each caller (ADR-0014's argument).
umask 077

export PATH='/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
# The extractors are subprocesses, and forking after the tokenizer has run makes it print a
# deadlock warning per document. Answering the question once here keeps the capture readable.
export TOKENIZERS_PARALLELISM=false

interpreter='/absolute/path/outside/this/repository/search-env/bin/python'
deployment='/absolute/path/outside/this/repository/deployment.json'
index_root='/absolute/path/outside/this/repository/search-index'
export_dir="$index_root/models/embeddinggemma-300m-onnx"
logs_dir='/absolute/path/outside/this/repository/logs'
capture='/absolute/path/outside/this/repository/logs/search.err.log'
capture_max_bytes=5242880

start_capture() {
  mkdir -p "$logs_dir" || exit 2
  chmod 700 "$logs_dir" || exit 2
  if [ -f "$capture" ] && [ "$(stat -f %z "$capture")" -ge "$capture_max_bytes" ]; then
    mv -f "$capture" "${capture%.log}.1.log"
  fi
  : >>"$capture" || exit 2
  chmod 600 "$capture" || exit 2
  exec >/dev/null 2>>"$capture"
}

refuse() {
  echo "syrax search pre-flight: $1" >&2
  exit 2
}

warn() {
  echo "syrax search pre-flight: $1" >&2
}

ensure_private() {
  local directory=$1
  mkdir -p "$directory" || refuse "$directory could not be created."
  chmod 700 "$directory" || refuse "$directory could not be made private."
}

check_interpreter() {
  [ -x "$interpreter" ] || refuse "$interpreter is not there: the environment was never created."
  "$interpreter" -c 'import syrax_search' 2>/dev/null ||
    refuse "the environment cannot import syrax_search."
}

# Every query is embedded before it is answered, so a missing export is not a narrower search but
# no search at all. Fetching it here would make an unattended start reach a network (ADR-0004).
check_export() {
  [ -f "$export_dir/model_q4.onnx" ] && [ -f "$export_dir/tokenizer.json" ] ||
    refuse "the pinned export is not in $export_dir; run 'fetch-embedder' once, deliberately."
}

# An empty index answers every query 'empty', which reads as a broken corpus rather than a first
# run. It is a warning and not a refusal: the unit has to be up for a pass to be poked into it.
check_index() {
  [ -f "$index_root/index.sqlite" ] || warn "no index yet; poke an index pass once this is up."
}

preflight() {
  ensure_private "$index_root"
  check_interpreter
  check_export
  check_index
}

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
  start_capture
  preflight
  exec "$interpreter" -m syrax_search serve "$deployment"
fi
