/**
 * The academic desk's wrapper, in the same shape as the other three (ADR-0005). What it runs is this
 * repository's own TypeScript from the checkout, as the lane monitor's does: the desk is Syrax's
 * code, where the gateway and the search unit are installed trees.
 *
 * Its pre-flight keeps the same asymmetry, and where it *warns* is the interesting half. A product
 * whose entrypoint is missing is a warning rather than a refusal, because the morning brief is the
 * system's daily heartbeat: a desk that refused to start over an unbuilt `academic-os` would turn a
 * product the Owner can fix in a minute into a silent morning, which is the one thing the brief is
 * defined not to be (ADR-0013). It starts, the brief goes out, and the brief says what did not run.
 */

import { join } from "node:path";
import type { Deployment } from "../adapter/deployment.ts";
import { academicOsEntrypoint, ntulearnEntrypoint } from "../academic/products.ts";
import { quoteForShell, wrapperPreamble } from "./wrapper.ts";

/** Named so it neither collides with the other captures nor matches the runtime's prune. */
export const academicCaptureBasename = "academic.err.log";

export function academicWrapperScript(
  deployment: Deployment,
  deploymentPath: string,
  checkout: string,
): string {
  const unit = join(checkout, "src", "cli", "serve-academic.ts");
  const products = deployment.academic;
  return `#!/bin/bash
# Generated by src/cli/install-academic-agent.ts. Regenerate it rather than edit it: every path below
# is a deployment's, and a hand edit is a decision recorded nowhere.
set -uo pipefail

# The desk's scratch holds one Proposal input at a time, and a Proposal input is the Owner's diary.
umask 077

${wrapperPreamble("syrax academic desk pre-flight", deployment.logsDir, join(deployment.logsDir, academicCaptureBasename))}

unit=${quoteForShell(unit)}
deployment=${quoteForShell(deploymentPath)}
academic_state=${quoteForShell(products?.academicState ?? "")}
secrets_store=${quoteForShell(deployment.secretsStore)}
academic_os=${quoteForShell(products === undefined ? "" : academicOsEntrypoint(products))}
ntulearn=${quoteForShell(products === undefined ? "" : ntulearnEntrypoint(products))}

ensure_private() {
  local directory=$1
  mkdir -p "$directory" || refuse "$directory could not be created."
  chmod 700 "$directory" || refuse "$directory could not be made private."
}

check_state() {
  [ -n "$academic_state" ] || refuse "the deployment names no academic products."
  ensure_private "$academic_state"
}

# ADR-0010: the store's mode is its protection, and this unit reads the bot token out of it to post
# the brief — so a readable store is refused here rather than at seven in the morning.
check_secrets_store() {
  local mode directory
  [ -f "$secrets_store" ] || refuse "$secrets_store is not there: the wizard has not run."
  mode=$(stat -f %Lp "$secrets_store")
  [ "$mode" = 600 ] || refuse "$secrets_store is mode $mode, expected 600."
  directory=$(dirname "$secrets_store")
  mode=$(stat -f %Lp "$directory")
  [ "$mode" = 700 ] || refuse "$directory is mode $mode, expected 700."
}

# A product that is not there answers nothing, and the brief says so on the morning it happens.
# Starting without one beats a heartbeat that stops for a checkout nobody has built yet.
check_products() {
  [ -f "$academic_os" ] || warn "$academic_os is not there: run npm ci && npm run build in academic-os."
  [ -f "$ntulearn" ] || warn "$ntulearn is not there: the ntulearn checkout is not where the deployment says."
}

preflight() {
  check_state
  check_secrets_store
  check_products
}

if [ "\${BASH_SOURCE[0]}" = "$0" ]; then
  start_capture
  preflight
  exec node "$unit" "$deployment"
fi
`;
}
