/**
 * The wrapper the LaunchAgent runs instead of the binary (ADR-0005), and the pre-flight it carries.
 *
 * It is generated rather than tracked for the same reason the configuration is (ADR-0019): every
 * path in it is machine-local, and a hand-edited copy is a decision that lives nowhere. The
 * pre-flight's two shapes are not interchangeable — ADR-0015 asserts a directory the runtime's own
 * resolver already creates at `0700`, and ADR-0017 ensures one that does not exist until a lock is
 * taken, because `mkdir -p` does not chmod what it finds.
 */

import { join } from "node:path";
import type { Deployment } from "../adapter/deployment.ts";
import { quoteForShell, wrapperPreamble } from "./wrapper.ts";

/**
 * What the gateway writes outside the runtime's own log — the pre-flight's lines, and whatever
 * kills the process. Named so it falls outside the runtime's own `openclaw-*` prune pattern.
 */
export const captureBasename = "gateway.err.log";

/** Hardcoded in the pinned runtime, which takes no setting for it (ADR-0015). */
export const scratchRoot = "/tmp/openclaw";

export function gatewayWrapperScript(deployment: Deployment): string {
  const runtime = join(deployment.runtimeRoot, "node_modules", "openclaw", "openclaw.mjs");
  return `#!/bin/bash
# Generated by src/cli/install-gateway-agent.ts. Regenerate it rather than edit it: every path below
# is a deployment's, and a hand edit is a decision recorded nowhere.
set -uo pipefail

# Everything below this line writes private runtime state, and the runtime creates its own
# directories with no mode at all (ADR-0014), so the mask is the floor rather than each caller.
umask 077

${wrapperPreamble("syrax pre-flight", deployment.logsDir, join(deployment.logsDir, captureBasename))}

export OPENCLAW_CONFIG_PATH=${quoteForShell(deployment.configPath)}
export OPENCLAW_STATE_DIR=${quoteForShell(deployment.stateDir)}

runtime=${quoteForShell(runtime)}
scratch_root=${quoteForShell(scratchRoot)}
lock_dir="\${TMPDIR:-/tmp}/openclaw-$(id -u)"

# ADR-0015: the runtime creates this at 0700 and then enforces only that nobody else can write it,
# so a world-readable scratch root passes its own check. Absent is fine — it creates it.
assert_private() {
  local directory=$1 mode
  [ -d "$directory" ] || return 0
  mode=$(stat -f %Lp "$directory")
  [ "$mode" = 700 ] || refuse "$directory is mode $mode, expected 700."
}

# ADR-0017: the lock directory does not exist until a lock is taken, so there is nothing to assert
# on a first run — and mkdir -p leaves an existing directory's mode alone.
ensure_private() {
  local directory=$1
  mkdir -p "$directory" || refuse "$directory could not be created."
  chmod 700 "$directory" || refuse "$directory could not be made private."
  assert_private "$directory"
}

# ADR-0010's asymmetry: an unresolved ref is a gateway that comes up and refuses every turn, which
# is worse than not coming up. A posture finding should not cost the Owner their chatbot.
audit_secrets() {
  local audited
  node "$runtime" secrets audit --check
  audited=$?
  case $audited in
    0) ;;
    1) warn "the secrets audit reports a posture finding; starting anyway." ;;
    *) refuse "the secrets audit exits $audited: a ref the runtime cannot resolve." ;;
  esac
}

# ADR-0005 closed this hole once and nothing has watched it since; off, a cut leaves the mini dark.
# It warns rather than refuses: a gateway that cannot survive a power cut still answers today.
check_restarts_after_power_loss() {
  local setting
  setting=$(pmset -g | awk '$1 == "autorestart" { print $2 }')
  [ "$setting" = 1 ] || warn "pmset autorestart is $setting: a power cut leaves the mini dark."
}

preflight() {
  assert_private "$scratch_root"
  ensure_private "$lock_dir"
  # The logs directory is not checked here: start_capture made it private before this ran.
  audit_secrets
  check_restarts_after_power_loss
}

if [ "\${BASH_SOURCE[0]}" = "$0" ]; then
  start_capture
  preflight
  exec node "$runtime" gateway
fi
`;
}
