/**
 * The lane monitor's wrapper, in the same shape as the other two (ADR-0005). What it runs is this
 * repository's own TypeScript, executed by Node from the checkout rather than from a root outside
 * it: the monitor is Syrax's code where the gateway and the search unit are installed trees, so
 * there is no third place for it to be installed into.
 *
 * Its pre-flight is the same asymmetry with this unit's own two checks. The state directory holds
 * counters that decide whether an allowance is still there, so a directory it cannot make private
 * is a refusal; and a secrets store that is missing or that the machine has left readable is
 * ADR-0010's refusal wherever it is met, here as everywhere.
 */

import { join } from "node:path";
import type { Deployment } from "../adapter/deployment.ts";
import { quoteForShell, wrapperPreamble } from "./wrapper.ts";

/** Named so it neither collides with the other captures nor matches the runtime's prune. */
export const monitorCaptureBasename = "monitor.err.log";

export function monitorWrapperScript(
  deployment: Deployment,
  deploymentPath: string,
  checkout: string,
): string {
  const unit = join(checkout, "src", "cli", "serve-monitor.ts");
  return `#!/bin/bash
# Generated by src/cli/install-monitor-agent.ts. Regenerate it rather than edit it: every path below
# is a deployment's, and a hand edit is a decision recorded nowhere.
set -uo pipefail

# The counters are private runtime state, and this unit creates the directory it writes them in.
umask 077

${wrapperPreamble("syrax lane monitor pre-flight", deployment.logsDir, join(deployment.logsDir, monitorCaptureBasename))}

unit=${quoteForShell(unit)}
deployment=${quoteForShell(deploymentPath)}
monitor_state=${quoteForShell(deployment.monitorState)}
secrets_store=${quoteForShell(deployment.secretsStore)}

ensure_private() {
  local directory=$1
  mkdir -p "$directory" || refuse "$directory could not be created."
  chmod 700 "$directory" || refuse "$directory could not be made private."
}

# A restart that lost the counters would hand back an allowance already spent, which is the whole
# reason this unit is separate — so the directory they live in is a refusal rather than a warning.
check_state() {
  ensure_private "$monitor_state"
}

# ADR-0010: the store's mode is its protection, so a readable one is refused rather than used. The
# hatch resolves the key at the moment it calls, and refusing here is refusing once instead.
check_secrets_store() {
  local mode
  [ -f "$secrets_store" ] || refuse "$secrets_store is not there: the wizard has not run."
  mode=$(stat -f %Lp "$secrets_store")
  [ "$mode" = 600 ] || refuse "$secrets_store is mode $mode, expected 600."
}

preflight() {
  check_state
  check_secrets_store
}

if [ "\${BASH_SOURCE[0]}" = "$0" ]; then
  start_capture
  preflight
  exec node "$unit" "$deployment"
fi
`;
}
