/**
 * The search unit's wrapper, in the same shape as the gateway's (ADR-0005) and built from the same
 * preamble: a script rather than a binary as the program, and a pre-flight that refuses rather than
 * starts wrong. `pdftotext`, `pdftoppm` and `tesseract` are Homebrew's, which is one of the two
 * reasons that preamble sets a `PATH` at all.
 *
 * What it refuses on is this unit's own. A missing export is not a degraded search but a search
 * that fails every query, since the query itself has to be embedded — so it is the gateway's
 * unresolvable-secret-ref case rather than its posture-finding case, and it exits 2.
 */

import { join } from "node:path";
import type { Deployment } from "../adapter/deployment.ts";
import { quoteForShell, wrapperPreamble } from "./wrapper.ts";

/** Named so it neither collides with the gateway's capture nor matches the runtime's prune. */
export const searchCaptureBasename = "search.err.log";

export function searchWrapperScript(deployment: Deployment, deploymentPath: string): string {
  const interpreter = join(deployment.searchRoot, "bin", "python");
  return `#!/bin/bash
# Generated by src/cli/install-search-agent.ts. Regenerate it rather than edit it: every path below
# is a deployment's, and a hand edit is a decision recorded nowhere.
set -uo pipefail

# The index holds the extracted text of private documents verbatim, and this unit creates the
# directories it writes. The mask is the floor rather than each caller (ADR-0014's argument).
umask 077

${wrapperPreamble("syrax search pre-flight", deployment.logsDir, join(deployment.logsDir, searchCaptureBasename))}

# The extractors are subprocesses, and forking after the tokenizer has run makes it print a
# deadlock warning per document. Answering the question once here keeps the capture readable.
export TOKENIZERS_PARALLELISM=false

interpreter=${quoteForShell(interpreter)}
deployment=${quoteForShell(deploymentPath)}
index_root=${quoteForShell(deployment.searchIndex)}
export_dir="$index_root/models/embeddinggemma-300m-onnx"

ensure_private() {
  local directory=$1
  mkdir -p "$directory" || refuse "$directory could not be created."
  chmod 700 "$directory" || refuse "$directory could not be made private."
}

check_interpreter() {
  [ -x "$interpreter" ] || refuse "$interpreter is not there: the environment was never created."
  "$interpreter" -c 'import syrax_search' 2>/dev/null ||
    refuse "the environment cannot import syrax_search."
}

# Every query is embedded before it is answered, so a missing export is not a narrower search but
# no search at all. Fetching it here would make an unattended start reach a network (ADR-0004).
check_export() {
  [ -f "$export_dir/model_q4.onnx" ] && [ -f "$export_dir/tokenizer.json" ] ||
    refuse "the pinned export is not in $export_dir; run 'fetch-embedder' once, deliberately."
}

# An empty index answers every query 'empty', which reads as a broken corpus rather than a first
# run. It is a warning and not a refusal: the unit has to be up for a pass to be poked into it.
check_index() {
  [ -f "$index_root/index.sqlite" ] || warn "no index yet; poke an index pass once this is up."
}

preflight() {
  ensure_private "$index_root"
  check_interpreter
  check_export
  check_index
}

if [ "\${BASH_SOURCE[0]}" = "$0" ]; then
  start_capture
  preflight
  exec "$interpreter" -m syrax_search serve "$deployment"
fi
`;
}
